### ISSUE TITLE
Error on installing from PowerShell Gallery

### ISSUE THREAD

**Issue by teramako** [teramako/Jagabata.psm#87]
```
PS1> Install-Module -Name Jagabata.psm -Scope CurrentUser
Install-Package: The following commands are already available on this system:'Get-Credential,Get-Host,Get-Job,Remove-Job'. 
This module 'Jagabata.psm' may override the existing commands. 
If you still want to install this module 'Jagabata.psm', use -AllowClobber parameter.
```

😢

**Comment by teramako** [comment]
# ToDo

- [x] Add command prefix
- [x] Upload package to Powershell Gallery
- [x] Create release note and add Zip package
